### ISSUE TITLE
Login page appears after logged in

### ISSUE THREAD

**Issue by andrewschultz** [jmacdotorg/ifcomp#47]
I tried to log in via

http://dev.ifcomp.org/auth/login

Then I opened up another tab and successfully logged in.

Then I refreshed tab#1 with http://dev.ifcomp.org/auth/login and it still asked me for my login name *and* said "Welcome, (username)!" Maybe it should kick you to the welcome page?

**Comment by jmacdotorg** [comment]
An interesting idea, but... I think if someone is that determined to see a login page, we should go ahead an show it to them. I'm can't think of a non-contrived path where someone would load /auth/login and expect to see something other than a login form.
