### ISSUE TITLE
48/72-hour warning

### ISSUE THREAD

**Issue by andrewschultz** [jmacdotorg/ifcomp#48]
Looking through @IFComp's tweets, I noticed the one where 37 people didn't vote for 5 games. Is there a (one-time) reminder in place with, say, 2-3 days left? So that if someone has opted in to emails, and they have voted on 1-4 games, they get a poke saying, they need to vote in X more games?

It would also be a neat courtesy to say "Thanks for voting, your votes will count" and maybe have something even more positive if someone manages to finish over half the games (as a competitor who tried to review other games, I believe that getting through half the games to vote for them is a strong accomplishment) or something for, say, <5 left.

Obviously you don't want to get extra oleaginous but I think it is the sort of nice thing that would make someone smile.

Also optional: mentioning you don't have to vote in all the games, if you're close. Some people are uncomfortable with a game or two, and I remember giving one game a very dashed off score in '10. So--this doesn't need to be a huge essay, but something natural and simple will probably work great.

The precise time to send the email is also up for grabs. But definitely give people time to play a few short works.

**Comment by jmacdotorg** [comment]
This is a good idea, thanks.

Instead of automating this, I'm going to make a note for myself to send a reminder to feet-dragging voters as the deadline draws near.
