### ISSUE TITLE
Typo on when to submit *any* file by

### ISSUE THREAD

**Issue by andrewschultz** [jmacdotorg/ifcomp#49]
http://dev.ifcomp.org/entry/1325/update

(or any # other than 1325)

mentions "Note that any entry without a main game file uploaded by 2015-09-26 will be effectively withdrawn automatically." <- should be 09-28

Also, 2 long adverbs in 3 words = minor stylistic thing. "...will (thus?) be withdrawn automatically."

**Comment by jmacdotorg** [comment]
This should be fixed now that the website is less chronically insane about date handling.
