### ISSUE TITLE
The "Play Online" button shouldn't appear if it's not going to work.

### ISSUE THREAD

**Issue by jmacdotorg** [jmacdotorg/ifcomp#52]
In the case of badly-prepared web-game uploads that have many files but no "index.html", a "Play Online" button will appear for then, and it will always 404.

**Comment by andrewschultz** [comment]
Just to check, this happens for Glulx/zcode games that happen to have feelies but not the whole directory structure.

Well, actually, *a* glulx game. Mine. *Gulp*

**Comment by jmacdotorg** [comment]
I'm closing this coz I'm gonna change how this works next year.
