### ISSUE TITLE
Recusal option for Miss Congeniality?

### ISSUE THREAD

**Issue by andrewschultz** [jmacdotorg/ifcomp#54]
I forget if it is there for judges. (I think it was?) But this would be a nice convenience so we have one more buffer to be sure we don't rate games we tested.

E.g.

None/1/2/3/4/5/6/7/8/9/10 becomes None/Recuse/1/2/3/4/5/6/7/8/9/10

It could also serve as a "not planned."

**Comment by jmacdotorg** [comment]
I thought about this earlier and decided against it; I don't like the idea of two menu options that both carry the same mechanical value, under the hypothesis that'd confuse more people than it'd please.
