### ISSUE TITLE
Judge opt-in mails for daily/weekly update list

### ISSUE THREAD

**Issue by andrewschultz** [jmacdotorg/ifcomp#56]
Very likely this is a bit too much for this year, but related to Peter Piers's question at http://www.intfiction.org/forum/viewtopic.php?f=32&t=18693&p=98295#p98295

This would be handy for people who want to see what changed. It could take the programmer logs and spin them into an appropriate mail.

Perhaps there could be an option for a big long summary on November 1st as well, so judges could pick off games that they put off due to bugs or whatever?

**Comment by jmacdotorg** [comment]
See #57.
