### ISSUE TITLE
Suggestion: more visible updates

### ISSUE THREAD

**Issue by PeterPiers** [jmacdotorg/ifcomp#57]
Currently, the updating system is completely silent; it seems an author can just update at will, and the entry will have a little note saying when the game was last updated.

This works wonders for the casual gamer, but I'd like to keep an up-to-date version of every game, as I have been for a few years now. It's quite difficult to follow as it is - my only option is to, every day, do a Ctrl-F to find the text "Updated: 1" for games updated on the first, "Updated: 2" for games updated on the second, etc.

It's not very nice. :) There are other ways of alleviating this that wouldn't affect the website (like, say, a post on IntFiction saying "New batch of updated games! The following games have received updates since xx/XX", but in-site I can think of a couple of ways to make it better.

 - Maybe if I could sort the games per update date? "Sort by most recently updated"?

 - An RSS feed, maybe? I could open it and instantly see which games have been updated.

Really, anything would work. As it is, it's, hmmm, well, again, just not very nice. :) I mean, it's great for people who just want to come in and play, but not so great for people who want to keep track of the updates and make sure to have an up-to-date version of each game for later consumption.

**Comment by jmacdotorg** [comment]
An RSS feed is a good idea! I'm adding it to the 2016 to-do list. Thanks.
