### ISSUE TITLE
Feature request: send zip file of game transcripts when comp is over

### ISSUE THREAD

**Issue by andrewschultz** [jmacdotorg/ifcomp#58]
This could be a nice way to encourage post-comp releases. While authors can access it during the comp, it may be useful for us to see patterns etc. Or it's quite possible that authors may give up on updating after a certain point. It is just one less thing to remember to track for those who want to update their game based on criticism, bugs, etc.

Maybe the authors could/should be asked to opt in, but it seems like a great resource.

**Comment by jmacdotorg** [comment]
acknowledged
